.TH MINI_SHELL 1 "2024-02-01" "1.0" "Mini Shell Manual"

.SH NAME
mini_shell \- a minimalistic shell program

.SH SYNOPSIS
.B mini_shell
[\fIOPTION\fR]...
[\fB-c\fR \fIcommand\fR]

.SH DESCRIPTION
Mini Shell is a simple command-line interpreter that allows users to execute commands and interact with the operating system.

.SH OPTIONS
.TP
.B \-c \fIcommand\fR
Executes the specified command in batch mode.

.SH AUTHOR
Written by DUVERNAY Benoit & GERBERON Alexandre.

.SH COPYRIGHT
Copyright (C) 2024 MEUCH
